<?php

/**
 * Implements hook_filter_info().
 */
function htmLawed_filter_info() {
  $filters['htmLawed'] = array(
    'title' => t('htmLawed (X)HTML filter/purifier'),
    'description' => t('make HTML markup in text secure and standard-compliant.'),
    'process callback' => '_htmLawed_process',
    'settings callback' => '_htmLawed_settings',
    'default settings' => array(
      'htmLawed' => array(
        'config' => "'safe'=>1, 'elements'=>'a, em, strong, cite, code, ol, ul, li, dl, dt, dd, br, p, table, tbody, td, tfoot, th, thead, tr', 'deny_attribute'=>'id, style'",
        'spec' => '',
        'help' => 'Tags allowed: a, em, strong, cite, code, ol, ul, li, dl, dt, dd, br, p, table, tbody, td, tfoot, th, thead, tr',
      ),
    ),
    'tips callback' => '_htmLawed_tips',
  );
  return $filters;
}

function _htmLawed_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  $settings = $filter->settings;
  // Filter by calling _htmLawed_process
  if (!empty($settings['htmLawed']['config'])) {
    eval('$config = array(' . $settings['htmLawed']['config'] . ');');
  }
  else {
    // config can't be ampty, so we set safe to 0, which is the same as leaving it empty
    $config = array('safe' => 0);
  }

  $module_path = drupal_get_path('module', 'htmLawed');
  include_once "$module_path/htmLawed/htmLawed.php";
  $text = htmLawed($text, $config, $settings['htmLawed']['spec']);

  return $text;
}

function _htmLawed_settings($form, &$form_state, $filter, $format, $defaults, $filters) {
  // Same key as in htmLawed_perm()
  if (!user_access('administer htmLawed (X)HTML filter/purifier')) {
    break;
  }
  $settings = $filter->settings + $defaults;

  $elements['htmLawed']['config'] = array(
    '#type' => 'textarea',
    '#rows' => '3',
    '#title' => t('Config.'),
    '#default_value' => $settings['htmLawed']['config'],
    '#description' => t('Comma-separated, quoted key-value pairs'),
  );
  $elements['htmLawed']['spec'] = array(
    '#type' => 'textarea',
    '#rows' => '3',
    '#title' => t('Spec.'),
    '#default_value' => $settings['htmLawed']['spec'],
    '#description' => t('Optional'),
  );
  $elements['htmLawed']['help'] = array(
    '#type' => 'textarea',
    '#rows' => '3',
    '#title' => t('Help'),
    '#default_value' => $settings['htmLawed']['help'],
    '#description' => t('Tips seen by users'),
  );

  return $elements;
}

/*
 * Display tips indicating htmLawed settings (elements allowed, etc.)
 */
function _htmLawed_tips($filter, $format, $long) {
  if ($long) {
    return t('HTML markup is restricted using the !htmLawed filter to make input text more secure, and standard- and admin. policy-compliant. More details about the restrictions in effect (that may vary from one content-type to another) may be available elsewhere, such as in the text of the input format filter-tips and on the input format configuration forms. For information on configuring htmLawed, visit the htmLawed !help section.', array('!help' => l(t('help'), 'admin/help/htmLawed')));
  }
  else {
    return t('HTML markup is restricted using the !htmLawed', array('!htmLawed' => l('htmLawed', 'http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/')));
  }
}

/*
 * Help page on module usage
 */
function htmLawed_help($path, $arg) { // Drupal 6 diff.
  switch ($path) {
    case 'admin/help#htmLawed':
      $help = '<p><strong>' . t('!htmLawed: PHP code to purify & filter HTML', array('!htmLawed' => l('htmLawed', 'http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/'))) . '</strong><p>' .
      '<ul>' .
        '<li>' . t('make HTML markup in text secure and standard-compliant') . '</li>' .
        '<li>' . t('process text for use in HTML, XHTML or XML documents') . '</li>' .
        '<li>' . t('balance tags, check element nesting, transform deprecated attributes and tags, make relative URLs absolute, etc.') . '</li>' .
        '<li><strong>' . t('fast, highly customizable, !documentation', array('!documentation' => l(t('well-documented'), 'http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawed_README.htm'))) . '</strong></li>' .
        '<li>' . t('single, 47 kb file') . '</li>' .
        '<li>' . t('simple HTML Tidy alternative') . '</li>' .
        '<li>' . t('free and licensed under LGPL') . '</li>' .
        '<li>' . t('use to filter, secure &amp; sanitize HTML in blog comments or forum posts, generate XML-compatible feed items from web-page excerpts, convert HTML to XHTML, pretty-print HTML, scrape web-pages, reduce spam, remove XSS code, etc.') . '</li>' .
      '</ul>';
      return $help;
  }
}
